# Generated by Django 5.2.6 on 2026-07-11 07:54

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_hips_measurement_biceps_measurement_calf_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=core.models.user_directory_path
            ),
        ),
    ]
